### ISSUE TITLE
Feature Request: Support on/off devices as sensors for rooms

### ISSUE THREAD

**Issue by durosity** [FlyingDiver/Indigo-Occupatum#20]
Request:
Ability to add other devices such as on/off devices as 'sensors' in an occupancy room

Reason:
I want to be able to 'lock' a room as being occupied so that it won't turn off.

Use Case:
Multiple, but one such example is my workshop where I restore old Macs.  I've got it setup to turn off after X mins of inactivity, but sometimes I'll deliberately want it to not turn off when a device like the ultrasonic cleaner is on, or if I'm leaving a machine running to see if a repair has worked.  

Considered Work Arounds:
Cancelling timers, but the problem is that as soon as motion is detected again it resumes countdown.  Also I want to be able to see at a glance that I left that room 'locked on' so an On/Off device would be ideal for that.

If you have any other potential ways of working this I'm all ears.

**Comment by FlyingDiver** [comment]
Use Masquerade plugin to make a sensor device from your relay device.

**Comment by durosity** [comment]
Ideally I'd rather not use masquerade.  I've already got about 30 of them for various other items like motion sensors, and it's becoming rather cumbersome to manage.  However if that's the only way.. ¯\_(ツ)_/¯

**Comment by FlyingDiver** [comment]
I really don't see any upside to complicating the plugin more when that's the sort of thing that Masquerade was designed for.  Put them all in a folder of their own and ignore them.
