### ISSUE TITLE
Timer count down in state column

### ISSUE THREAD

**Issue by tazswe** [FlyingDiver/Indigo-Occupatum#6]
Instead of showing on it could show remaining time before it goes of.

**Comment by FlyingDiver** [comment]
Still to be looked at.

**Comment by FlyingDiver** [comment]
Not possible with current plugin design.

**Comment by FlyingDiver** [comment]
Had another user request this.  I'm going to reopen this so I can think about how to do this without redesigning the whole system.  No promises.

**Comment by FlyingDiver** [comment]
There's two possible timers associated with any zone.  The delay timer (delay before turning on/off), and the force off timer.  Both could be active at the same time.  Not sure how to handle that.

**Comment by FlyingDiver** [comment]
Try this:  https://github.com/FlyingDiver/Indigo-Occupatum/archive/refs/heads/timer-states.zip

**Comment by FlyingDiver** [comment]
Try this:  https://github.com/FlyingDiver/Indigo-Occupatum/releases/tag/2022.1.0b1

**Comment by FlyingDiver** [comment]
Waiting on feedback.
