### ISSUE TITLE
alternate definitions of 'Occupied' based on cumulative inputs over a span of time

### ISSUE THREAD

**Issue by rbdubz3** [FlyingDiver/Indigo-Occupatum#9]
For some automations it'd be useful to relax the definition of 'Occupied' to include cumulative inputs over a span of time. The rationale here is to minimize 'false' positives and attempt to ensure that someone is really in the specific room/zone rather than just momentarily passing thru. A couple of algos I've experimented with in my house via custom scripts:
1) Count of 'Sensor ON' trigger over a span of time - such as 5 triggers in 10 min
2) Total count of 'Seconds with motion ON' over a time interval - such as 120 seconds in 10 min

I've used this in my house for controlling Ceiling Fans and small space heaters. Essentially I didn't wanna keep flipping these ON (or OFF) unless I was pretty sure the room was occupied (or empty).

**Comment by rbdubz3** [comment]
My custom script implementation notes:

**Count of Triggers Algo**: 
- Device Settings : user specifies the Thresholds for 'Activation Time in min' and 'Activation Count'
- state management : 'initial sensor activation timestamp' and 'current activation count'  
- implementation: Each sensor ON activation is counted if the room isn't occupied. If the current activation count matches the total specified in the device settings, and the current timestamp is within 'Activation Time min' from the 'initial sensor activation timestamp' - the room is considered Occupied.. If the sensor activation isn't within the 'Activation Time min' the state variables are reset and it starts all over. **TBH** the proper implementation is to track every sensor activation timestamp so that you can make determinations on a rolling basis. Since I was handling custom scripts I didn't attempt to get fancy with storing collections of data

**Total count of 'Seconds with motion ON' Algo**: 
- Device Settings : user specifies the Thresholds for 'Activation Time in min' and 'Activation Seconds'
- state management : 'last sensor activation timestamp' and 'total seconds sensor is ON'  
- implementation: If the room isn't occupied - each sensor ON activation triggers logic to store the activation timestamp. Each sensor OFF triggers a separate logic to compute the 'seconds of activation' and add it to a cumulative total.  If the cumulative total exceeds the total specified in the device settings, and the current timestamp is within 'Activation Time min' from the 'initial sensor activation timestamp' - the room is considered Occupied. This also required an additional timer to run while trying to figure out activation - the timer was used to account for a long sensor activation that didn't go OFF for several minutes - hence the timer would periodically wake up and attribute seconds towards the occupancy goal and set the state to 'Occupied' . Similar to the other algo -  the proper implementation is to track every sensor activation timestamp so that you can make determinations on a rolling basis. Since I was handling custom scripts I didn't attempt to get fancy with storing collections of data

BTW - there may be a better approach that combines these 2 algos somehow. Also I'm not sure my wall of text above is super helpful but I'd be happy to break it down further.. Also I'd be happy to do the implementation (but may take me a while since i'm still working full time and this is my off-hours hobby).

**Comment by FlyingDiver** [comment]
Hmm.  Tricky.  I'll have to think on this.  Not going to start coding anything until I get the current WIP released.

**Comment by rbdubz3** [comment]
Yeah no worries at all Joe. As I mentioned I may start to hack on it in my spare time - i'll take a fork off your repo

**Comment by FlyingDiver** [comment]
I've already created a branch and am prototyping some code.  Not sure if it'll go anywhere yet.

**Comment by FlyingDiver** [comment]
Wait a day or two before forking, as I'll be merging a dev branch in soon.

**Comment by FlyingDiver** [comment]
Give this a try:  https://github.com/FlyingDiver/Indigo-Occupatum/releases/tag/2022.1.0b1

**Comment by FlyingDiver** [comment]
Have you had a chance to try this yet?

**Comment by rbdubz3** [comment]
ah my bad Joe - caught up in my work-week and didn't see that last update.. Lemme give it a whirl this weekend.. Thanks!

**Comment by rbdubz3** [comment]
Ok - took it for a quick test spin - looks good so far .. Thanks Joe!

Question - once 'occupied = True' for an Activity Zone - how long does it remain in this state? Or is the plugin doing the activity zone checking on a continuous 'rolling interval' basis?

**Comment by FlyingDiver** [comment]
Rolling interval.  As soon as the count of activations in the window goes below the threshold it'll turn off.

**Comment by FlyingDiver** [comment]
How's the timer countdown look to you?

**Comment by rbdubz3** [comment]
It seems like it's working from what I can tell - i haven't checked specific timings as such.. BTW is there anywhere I can observe the timer countdown state?

**Comment by FlyingDiver** [comment]
There's no specific state for the countdown, it's calculated every update from current time and timer expiration.

**Comment by FlyingDiver** [comment]
Oh wait, I did put that in.  It's the delay_timer state.

**Comment by rbdubz3** [comment]
Oh ok cool - thanks again Joe.. I'll integrate this into some of my automations and let you know how it works.. Thanks again!

BTW - Not expecting you to work on that other implementation for 'Total Time(seconds) over an interval' .. But i did find this useful in my own setup.. It seemed in scenarios where I was sitting at my desk but NOT moving, the motion detectors remained in the ON state for an extended period of time. Hence I didn't quite hit my threshold of X motion detections in Y minutes.. It'd be interesting to support of 1 or the other modes - in addition to an either/or mix of these models for the Activity Zone.. i.e. 10 motion activations OR 120 seconds over the Time Window

**Comment by FlyingDiver** [comment]
The total time would be a lot harder, because then I would need to keep track of the specific sensor's activation time and match it with a deactivation.  Just counting activations is pretty simple.

**Comment by FlyingDiver** [comment]
Closing for now, but feel free to reopen if you have issues.
